### ISSUE TITLE
ModuleNotFoundError: No module named 'flair'

### ISSUE THREAD

**Issue by makamkkumar** [Hellisotherpeople/CX_DB8#11]
I am getting a peculiar error for the connabd
$ **python -i cx_db8_flair.py** 
_Traceback (most recent call last):
  File "cx_db8_flair.py", line 2, in <module>
    import flair
ModuleNotFoundError: No module named 'flair'_
>>> 
Incidentally, it comes and rests at a python prompt
The output of the command 
$ **pip list** 
is given below and flair package is installed as required.
_Package                       Version  
----------------------------- ---------
absl-py                       0.7.1    
alabaster                     0.7.12   
allennlp                      0.6.0    
astor                         0.7.1    
atomicwrites                  1.3.0    
attrs                         19.1.0   
awscli                        1.16.260 
Babel                         2.7.0    
backcall                      0.1.0    
bert-tensorflow               1.0.1    
bleach                        3.1.0    
boto                          2.49.0   
boto3                         1.9.231  
botocore                      1.12.250 
bpemb                         0.3.0    
bunch                         1.0.1    
certifi                       2019.6.16
cffi                          1.11.2   
chardet                       3.0.4    
Click                         7.0      
colorama                      0.4.1    
conllu                        0.11     
cycler                        0.10.0   
cymem                         2.0.2    
cytoolz                       0.9.0.1  
decorator                     4.4.0    
defusedxml                    0.5.0    
Deprecated                    1.2.6    
dill                          0.2.9    
docutils                      0.15.2   
editdistance                  0.5.3    
entrypoints                   0.3      
**flair                         0.4.2**    
flaky                         3.6.1    
Flask                         0.12.1   
Flask-Cors                    3.0.3    
future                        0.17.1   
gast                          0.2.2    
gensim                        3.8.1    
gevent                        1.3.5    
googleapis-common-protos      1.5.10   
greenlet                      0.4.15   
grpcio                        1.14.1   
h5py                          2.9.0    
hyperopt                      0.1.2    
idna                          2.8      
imagesize                     1.1.0    
importlib-metadata            0.23     
ipykernel                     5.1.1    
ipython                       7.7.0    
ipython-genutils              0.2.0    
itsdangerous                  1.1.0    
jedi                          0.14.1   
Jinja2                        2.10.1   
jmespath                      0.9.4    
joblib                        0.13.2   
jsonnet                       0.10.0   
jsonschema                    3.0.1    
jupyter-client                5.3.1    
jupyter-core                  4.4.0    
Keras                         2.2.4    
Keras-Applications            1.0.7    
keras-models                  0.0.2    
Keras-Preprocessing           1.0.9    
keras-vggface                 0.6      
kiwisolver                    1.1.0    
Mako                          1.0.10   
Markdown                      3.1      
MarkupSafe                    1.1.1    
matplotlib                    3.1.1    
mistune                       0.8.4    
mkl-fft                       1.0.12   
mkl-random                    1.0.2    
mock                          2.0.0    
more-itertools                7.2.0    
mpld3                         0.3      
msgpack                       0.5.6    
msgpack-numpy                 0.4.3.2  
murmurhash                    1.0.2    
nbconvert                     5.5.0    
nbformat                      4.4.0    
networkx                      2.3      
nltk                          3.4.5    
notebook                      5.7.8    
numpy                         1.16.3   
numpydoc                      0.8.0    
opencv-python                 4.1.0.25 
overrides                     2.0      
packaging                     19.2     
pandas                        0.25.0   
pandocfilters                 1.4.2    
parsimonious                  0.8.0    
parso                         0.5.1    
pbr                           5.1.3    
pexpect                       4.7.0    
pickleshare                   0.7.5    
Pillow                        6.1.0    
pip                           19.1     
plac                          0.9.6    
pluggy                        0.13.0   
preshed                       2.0.1    
prometheus-client             0.7.1    
promise                       2.2.1    
prompt-toolkit                2.0.9    
protobuf                      3.7.1    
psutil                        5.6.3    
ptyprocess                    0.6.0    
py                            1.8.0    
pyasn1                        0.4.7    
pycparser                     2.19     
Pygments                      2.4.2    
pygpu                         0.7.6    
pymongo                       3.9.0    
pyparsing                     2.4.2    
pyrsistent                    0.15.4   
pytest                        5.2.1    
python-dateutil               2.8.0    
pytorch-pretrained-bert       0.6.2    
pytorch-transformers          1.2.0    
pytz                          2017.3   
PyYAML                        5.1.2    
pyzmq                         18.0.2   
regex                         2018.1.10
requests                      2.21.0   
responses                     0.10.6   
rouge                         0.3.2    
rsa                           3.4.2    
s3transfer                    0.2.1    
sacremoses                    0.0.33   
scikit-learn                  0.21.3   
scipy                         1.2.1    
segtok                        1.5.7    
Send2Trash                    1.5.0    
sentencepiece                 0.1.83   
setuptools                    41.0.1   
six                           1.12.0   
sklearn                       0.0      
smart-open                    1.8.4    
snowballstemmer               2.0.0    
spacy                         2.0.18   
Sphinx                        2.2.0    
sphinxcontrib-applehelp       1.0.1    
sphinxcontrib-devhelp         1.0.1    
sphinxcontrib-htmlhelp        1.0.2    
sphinxcontrib-jsmath          1.0.1    
sphinxcontrib-qthelp          1.0.2    
sphinxcontrib-serializinghtml 1.1.3    
sqlitedict                    1.6.0    
tabulate                      0.8.5    
tensorboard                   1.13.1   
tensorboardX                  1.2      
tensorflow                    1.13.1   
tensorflow-datasets           1.0.2    
tensorflow-estimator          1.13.0   
tensorflow-hub                0.6.0    
tensorflow-metadata           0.13.0   
termcolor                     1.1.0    
terminado                     0.8.2    
testpath                      0.4.2    
Theano                        1.0.3    
thinc                         6.12.1   
toolz                         0.10.0   
torch                         1.3.0    
tornado                       6.0.3    
tqdm                          4.31.1   
traitlets                     4.3.2    
typing                        3.7.4.1  
ujson                         1.35     
Unidecode                     1.1.1    
urllib3                       1.24.2   
wcwidth                       0.1.7    
webencodings                  0.5.1    
Werkzeug                      0.15.2   
wheel                         0.33.1   
wrapt                         1.10.11  
zipp                          0.6.0_ 
Solutions are welcome. Can anyone please give a solution.

**Comment by Hellisotherpeople** [comment]
Try running pip install flair --update as you need to use flair version 4.3

If that still doesn't help please let me know. Worst case is that you can git clone flair, and put the cx_db8 code into that flair folder and it should work then too
