### ISSUE TITLE
Why Linux?

### ISSUE THREAD

**Issue by Isaacium** [Hellisotherpeople/CX_DB8#4]
Why is Linux necessary to use this? Could I not just use pip and Python on Windows without having to install a Linux distro?

**Comment by Hellisotherpeople** [comment]
You're welcome to try!

I assumed that somewhere there's a package that I'm using that wouldn't work on windows

 I have never personally ran this or Python on windows. If you get this successfully working on windows, please let me know and I'll update the install instruction

**Comment by Hellisotherpeople** [comment]
Just tested on my own end - Windows WORKS - but the formatting in the default terminal and powershell doesn't display. I suspect that a better terminal emulator will support Sty's underlining and highlighting. 

The important part is that windows users can utilize CX_DB8 to create word docs on the fly.

**Comment by Isaacium** [comment]
I tried it on Windows as well, and it created GENERATED SUMMARY and NOT UNDERLINED sections. It did not generate a word document. Something may not be installed right on my end, I will take a look at it again later. I also tried it in Git Bash, but Ctrl-D did not stop text entry and I could not figure out what keys would stop it.

**Comment by Hellisotherpeople** [comment]
Look for "test_sum.docx", that is where the docx should be. Works on my machine :) 

On windows, it's (Ctrl-Z + Enter)

As far as it not highlighting or underlining, I have no idea why that is. I will try it again with dynamic underlining/highlighting turned off. I suspect that it's an issue somewhere within Sty (the terminal highlighting library)
